### ISSUE TITLE
AutoDDU niche cases checklist

### ISSUE THREAD

**Issue by Evernow** [CommandMC/24HS-Automator#3]
This is meant to track niche cases which AutoDDU should be able to handle at some point. 

- [ ] Handle cases where people overwrite the install location of applications in Windows outside of the C: drive. [This causes permissions issues](https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/336449/windows-cannot-access-the-specified-device-path-or/). I have been looking into this, haven't found where in registry it's stored yet.
- [ ] Allow user to specify if they want to provide a driver of their own instead of using the latest in our repo. This is useful for when we either forget to update the driver, or someone wants to try a different driver to see if their issue is present.
- [ ] Turn off Link State Power Management for non-laptop setups. Mainly because [this can cause annoying as hell stability issues](https://discord.com/channels/185647255028629505/185808757115191296/920597632118829076). There is no real problem with disabling this on desktops, barely increases power usage. On laptops however this can cause the GPU to be on 100% of the time. 
- [ ] Verify there is at least 20GB of free space on C: prior to doing anything.
- [ ] Disable all overclocking crap. This can be the cause of their issue to begin with, this is already handled in my draft.
- [ ] There are setups where people have multiple different GPUs of the same vendor, this can cause issues during installation due to [this configuration obviously being a headache](https://nvidia.custhelp.com/app/answers/detail/a_id/2280/~/can-i-use-a-geforce-and-quadro-card-in-the-same-system%3F). This should be careful to handle laptops and GPUs like the GTX 690. 
- [ ] Make sure someone's system time is correct. I have a working implementation of this that uses NTP servers. This is to catch connection issues that prevent from downloading drivers, it can happen when a PC has not been turned on for a long time.
- [ ] Handle LTSC/LTSB installs and update them. I have a working implementation of this already.
- [ ] After running DDU and installing drivers Auto-DDU should select highest resolution/refresh rate for all monitors and enable GSync if applicable 
- [ ] Block Windows Updates from installing drivers after exiting safe mode, ideally this is done by simply blocking internet access. Note we need an exception for Intel as their driver install utility requires internet. So if someone has an Intel and NVIDIA system, we install NVIDIA driver first, then turn on internet and install Intel.
- [ ] Make sure it works with stupid OneDrive configured crap
- [ ] Handle EOL cases and different GPU branches (Enterprise for AMD, R390/R470 for NVIDIA)
- [ ] You cannot enter safe mode if you have bitlocker enabled without the user inputting their BitLocker recovery key manually. We can probably avoid this by just temporarily suspending bitlocker before rebooting the user, said user should be informed of this.
- [ ] Turn off custom CRU resolutions, should be a simple [download then run reset all command](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU)
